/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guntass Kaur
 */
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import vmm.DBLoader;

public class AdminManageCars extends javax.swing.JFrame {

    /**
     * Creates new form AdminManageCars
     */
    ArrayList<car_details> al = new ArrayList<>();

    public AdminManageCars() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(240, 248, 255));
        jTable1.getTableHeader().setFont(new java.awt.Font("Verdana", java.awt.Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(new java.awt.Color(13, 71, 161));
        setTitle("AdminManageCars");
        loadCarData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("Already Added Cars");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 10, 500, 83);

        jButton1.setBackground(new java.awt.Color(37, 99, 235));
        jButton1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add New Car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 530, 200, 45);

        jButton2.setBackground(new java.awt.Color(37, 99, 235));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Remove Car");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 530, 200, 45);

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 120, 930, 350);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-94.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 100, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminAddCar obj = new AdminAddCar();
        obj.setVisible(true);
        AdminManageCars obj1 = new AdminManageCars();
        obj1.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();
        System.out.println(i);
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row");
        } else {
            int car_id = al.get(i).carid;
            System.out.println(car_id);
            try {
                ResultSet rs = DBLoader.executeQuery("select * from cabbooking.car_details where car_id = " + car_id + " ");
                if (rs.next()) {
                    int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete it?", "", JOptionPane.YES_NO_OPTION);
                    if (a == JOptionPane.YES_OPTION) {

                        rs.deleteRow();
                        loadCarData();
                        JOptionPane.showMessageDialog(this, "Deleted Successfully");

                    } else {
                        JOptionPane.showMessageDialog(this, "NO Clicked");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Deleted Failed");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      AdminHome obj1=new AdminHome();
      obj1.setVisible(true);
      dispose();

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public class car_details {

        public int carid;
        public String car_names;
        public String brand;
        public String car_type;
        public String fuel_type;
        public int price_without_driver;
        public int price_with_driver;
        public int security;
        public String description;
        public String name_plate;

        public car_details(int carid, String car_names, String brand, String car_type, String fuel_type,
                int price_without_driver, int price_with_driver,
                int security, String description, String name_plate) {
            this.carid = carid;
            this.car_names = car_names;
            this.brand = brand;
            this.car_type = car_type;
            this.fuel_type = fuel_type;
            this.price_without_driver = price_without_driver;
            this.price_with_driver = price_with_driver;
            this.security = security;
            this.description = description;
            this.name_plate = name_plate;
        }
    }
// This method goes in your AdminManageCars class

    private void loadCarData() {
        try {
            al.clear(); // clear old data
            ResultSet rs = DBLoader.executeQuery("SELECT * FROM car_details");

            while (rs.next()) {
                int cid = (rs.getInt("car_id"));
                String cn = rs.getString("car_names");
                String bd = rs.getString("brand");
                String ct = rs.getString("car_type");
                String ft = rs.getString("fuel_type");
                int pwd = Integer.parseInt(rs.getString("price_per_day_without_driver"));
                int pd = Integer.parseInt(rs.getString("price_per_day_with_driver"));
                int s = Integer.parseInt(rs.getString("security"));

                String ds = rs.getString("description");

                String nm = rs.getString("name_plate");

                al.add(new car_details(cid, cn, bd, ct, ft, pwd, pd, s, ds, nm));
            }

            jTable1.setModel(new CarTableModel());

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading car data.");
        }
    }

    class CarTableModel extends AbstractTableModel {

        String[] headers = {"Car Name", "Brand", "Type", "Fuel", "Without Driver", "With Driver", "Security", "Description", "Plate"};

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return headers.length;
        }

        @Override
        public String getColumnName(int col) {
            return headers[col];
        }

        @Override

        public Object getValueAt(int i, int j) {
            car_details obj = al.get(i);

            if (j == 0) {
                return obj.car_names;
            } else if (j == 1) {
                return obj.brand;
            } else if (j == 2) {
                return obj.car_type;
            } else if (j == 3) {
                return obj.fuel_type;
            } else if (j == 4) {
                return obj.price_without_driver;
            } else if (j == 5) {
                return obj.price_with_driver;
            } else if (j == 6) {
                return obj.security;
            } else if (j == 7) {
                return obj.description;
            } else {
                return obj.name_plate;
            }
        }
    }
}
