
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Guntass Kaur
 */
public class Booking extends javax.swing.JFrame {

    JFileChooser jfc;
    String path;
    File f;
    String id;
    String photo;
    String car_name;
    String brand;
    String description;
    String price_per_day_without_driver;
    String price_per_day_with_driver;
    String security;
    String car_type;

    public Booking(String id, String photo, String car_name, String brand, String description, String price_per_day_without_driver, String price_per_day_with_driver, String security, String car_type) {
        initComponents();
        setSize(850, 1490);
        setLocationRelativeTo(null);
        setTitle("Booking");

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);

        this.id = id;
        this.photo = photo;
        this.car_name = car_name;
        this.brand = brand;
        this.description = description;
        this.price_per_day_without_driver = price_per_day_without_driver;
        this.price_per_day_with_driver = price_per_day_with_driver;
        this.security = security;
        this.car_type = car_type;
        jLabel11.setText(car_name);
        jLabel12.setText(description);
        jLabel13.setText(brand);
        jLabel14.setText(security);
        jRadioButton1.setText(price_per_day_without_driver);
        jRadioButton2.setText(price_per_day_with_driver);

        path = photo;
        ImageIcon i1 = new ImageIcon(path);
        Image img = i1.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(img);
        jLabel2.setIcon(i2);
        setSize(700, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jd1 = new com.toedter.calendar.JDateChooser();
        jd2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 0, 271, 60);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 260, 260);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 99, 235));
        jLabel3.setText("Description :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 130, 150, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 99, 235));
        jLabel4.setText("Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 80, 150, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 99, 235));
        jLabel5.setText("Brand :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 180, 150, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 99, 235));
        jLabel6.setText("Price without Driver :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 330, 260, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 99, 235));
        jLabel7.setText("Price with Driver :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 380, 260, 50);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 99, 235));
        jLabel8.setText("From Date :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 440, 146, 37);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 99, 235));
        jLabel9.setText("To Date :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 500, 146, 37);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 99, 235));
        jLabel10.setText("Security :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 230, 150, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 130, 600, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 80, 500, 30);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 180, 500, 30);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(430, 230, 500, 30);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(330, 330, 130, 34);

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(330, 380, 126, 36);
        getContentPane().add(jd1);
        jd1.setBounds(330, 440, 200, 40);
        getContentPane().add(jd2);
        jd2.setBounds(330, 500, 200, 40);

        jButton1.setBackground(new java.awt.Color(37, 99, 235));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 590, 190, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-94.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 0, 94, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String price_per_day = "0";

        if (jRadioButton1.isSelected()) {
            System.out.println("You chose car without driver: " + jRadioButton1.getText());
            price_per_day = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected()) {
            System.out.println("You chose car with driver: " + jRadioButton2.getText());
            price_per_day = jRadioButton2.getText();
        } else {
            System.out.println("Please select a car option");
            return;
        }
           

        Date start_date_obj = jd1.getDate();
        Date end_date_obj = jd2.getDate();
   

        String start_date = (start_date_obj != null) ? start_date_obj.toString() : null;
        String end_date = (end_date_obj != null) ? end_date_obj.toString() : null;

      

        String days = "0";
        String rent = "0";
        long no_of_days;
        if (start_date_obj == null || end_date_obj == null) {
            System.out.println("Please select both dates");
        } else if (start_date_obj.after(end_date_obj)) {
            System.out.println("Please enter a valid date. Start date can't be after end date");
        } else {
            System.out.println("Valid date range");

            long diff = end_date_obj.getTime() - start_date_obj.getTime();
            no_of_days = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS) + 1;

            days = String.valueOf(no_of_days);

            int priceInt = Integer.parseInt(price_per_day);
            long rentAmount = priceInt * no_of_days;
            rent = String.valueOf(rentAmount);

            System.out.println("Days between: " + days);
            System.out.println("Total Rent: " + rent);
        }
dispose();
       BookCar obj = new BookCar(id,price_per_day,start_date,end_date, days, rent,security);
     
obj.setVisible(true);
 


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        UserHome obj = new UserHome();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking("", "", "", "", "", "", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private com.toedter.calendar.JDateChooser jd1;
    private com.toedter.calendar.JDateChooser jd2;
    // End of variables declaration//GEN-END:variables

}
