


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Guntass Kaur
 */
public class CarDesign extends javax.swing.JPanel {

    /**
     * Creates new form CarDesign
     */
    public CarDesign() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lb1.setText("jlabel1");
        add(lb1);
        lb1.setBounds(6, 40, 420, 390);

        lb2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(37, 99, 235));
        lb2.setText("jLabel2");
        add(lb2);
        lb2.setBounds(440, 20, 620, 90);

        lb3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(37, 99, 235));
        lb3.setText("jLabel3");
        add(lb3);
        lb3.setBounds(440, 100, 650, 90);

        lb4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb4.setForeground(new java.awt.Color(37, 99, 235));
        lb4.setText("jLabel4");
        add(lb4);
        lb4.setBounds(440, 180, 650, 90);

        lb5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb5.setForeground(new java.awt.Color(37, 99, 235));
        lb5.setText("jLabel1");
        add(lb5);
        lb5.setBounds(440, 280, 760, 90);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel lb4;
    public javax.swing.JLabel lb5;
    // End of variables declaration//GEN-END:variables
}
