import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import vmm.DBLoader;
import java.sql.*;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Guntass Kaur
 */

public class UserBookingHistory extends javax.swing.JFrame {
ArrayList<BookingDetails> al = new ArrayList<>();
    /**
     * Creates new form UserBookingHistory
     */
    public UserBookingHistory() {
        initComponents();
         getContentPane().setBackground( new Color(240,248,255));
        jTable1.getTableHeader().setFont(new java.awt.Font("Verdana",java.awt.Font.BOLD,12));
        jTable1.getTableHeader().setForeground(new java.awt.Color(13,71,161));
        setTitle("User Booking History");
        setExtendedState(MAXIMIZED_BOTH);
loadBookingData();
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 245, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("YOUR BOOKING HISTORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 740, 52);

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 1280, 530);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-94.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       UserHome obj1=new UserHome();
       obj1.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBookingHistory().setVisible(true);
            }
});
}
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 private void loadBookingData() {
        try {
            al.clear(); // clear old data
            ResultSet rs = DBLoader.executeQuery("SELECT * FROM booking");

            while (rs.next()) {
                int bd = (rs.getInt("booking_id"));
                int cid = (rs.getInt("car_id"));
                int pp = (rs.getInt("price_per_day"));
                String sd = rs.getString("start_date");
                String ed = rs.getString("end_date");
                int nd = (rs.getInt("no_of_days"));
                int r = (rs.getInt("rent"));
                int s = Integer.parseInt(rs.getString("security"));
                String n = rs.getString("name");
                String m = rs.getString("mobile_no");
                String add = rs.getString("address");
                String em = rs.getString("email");
                String ps = rs.getString("payment_status");
                String booking = rs.getString("booking_status");
 al.add(new BookingDetails(bd, cid, pp, sd, ed, nd, r, s, n, m, add, em, ps, booking));

            
            }
  jTable1.setModel(new UserBookingModel());

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading car data.");
        }
}
    


    class UserBookingModel extends AbstractTableModel {

        String[] headers = {"Carid", "PricePerDay", "Start Date", "End date", "No of Days", "Rent", "Security", "Name", "Mobile no", "Address", "Email", "Payment Status", "Booking Status"};

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return headers.length;
        }

        @Override
        public String getColumnName(int col) {
            return headers[col];
        }

        @Override

        public Object getValueAt(int i, int j) {
            BookingDetails obj = al.get(i);

            if (j == 0) {
                return obj.carid;
            } else if (j == 1) {
                return obj.priceperday;
            } else if (j == 2) {
                return obj.start_date;
            } else if (j == 3) {
                return obj.end_date;
            } else if (j == 4) {
                return obj.no_of_days;
            } else if (j == 5) {
                return obj.rent;
            } else if (j == 6) {
                return obj.security;
            } else if (j == 7) {
                return obj.name;
            } else if (j == 8) {
                return obj.mobile_no;
            } else if (j == 9) {
                return obj.address;
            } else if (j == 10) {
                return obj.email;
            } else if (j == 11) {
                return obj.payment_status;
            } else {
                return obj.booking_status;
            }

        }}
}
    
