
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import vmm.DBLoader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Guntass Kaur
 */
public class UserSignup extends javax.swing.JFrame {

    /**
     * Creates new form UserSignup
     */
    public UserSignup() {
        initComponents();
           getContentPane().setBackground( new Color(240,248,255));
        
        getContentPane().setBackground( new Color(240,248,255));
        setSize(500, 500);
        setLocationRelativeTo(null);
        setTitle("User Signup");
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(211, 216, 224));
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("USER SIGNUP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 310, 45);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 99, 235));
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 160, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 99, 235));
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 127, 160, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 99, 235));
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 175, 160, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 99, 235));
        jLabel5.setText("Confirm Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 225, 160, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 99, 235));
        jLabel6.setText("Mobile Number :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 275, 160, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 99, 235));
        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 322, 160, 30);

        jButton1.setBackground(new java.awt.Color(255, 152, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 390, 130, 35);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 80, 200, 30);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 127, 200, 30);

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(250, 175, 200, 30);

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jPasswordField2.setText("jPasswordField2");
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(250, 225, 200, 30);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 275, 200, 30);

        jRadioButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton1.setText("Female");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(350, 322, 100, 30);

        jRadioButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton3.setText("Male");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(250, 322, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String u = jTextField1.getText().trim();
            String e = jTextField2.getText().trim();
            String p = jPasswordField1.getText().trim();
            String cp = jPasswordField2.getText().trim(); 
            String m = jTextField3.getText().trim();

String error = InputValidator.validateAll(u,e,m);

if (error != null) {
    JOptionPane.showMessageDialog(null, error, "Validation Error", JOptionPane.ERROR_MESSAGE);
    return;
}
  
    if (!InputValidator.doPasswordsMatch(p, cp)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


    if (!InputValidator.isGenderSelected(jRadioButton3, jRadioButton1)) {
        JOptionPane.showMessageDialog(this, "Please select a gender.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


            String g = "";
            //String g=rd2.getText();
            if (jRadioButton3.isSelected()) {
                g = "male";
            } else {
                g = "female";
            }

            ResultSet rs = DBLoader.executeQuery("select * from user where email='" + e + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Email already exists");
            } else {

                rs.moveToInsertRow();
                rs.updateString("username", u);
                rs.updateString("email", e);
                rs.updateString("password", p);
                rs.updateString("mobileno", m);
                rs.updateString("gender", g);
                rs.insertRow();
                System.out.println("Row inserted succesfully");
                JOptionPane.showMessageDialog(this, "Signup Successfully Successful!");

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        UserHome obj=new UserHome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignup().setVisible(true);
            }
        });
    }
   public class InputValidator {

    // Count digits in a string
    public static int countDigits(String input) {
        if (input == null) return 0;

        int digitCount = 0;
        for (char ch : input.toCharArray()) {
            if (Character.isDigit(ch)) {
                digitCount++;
            }
        }
        return digitCount;
    }

   
    public static boolean isValidName(String name) {
        return name != null && name.trim().length() >= 2;
    }

  
    public static boolean isValidEmail(String email) {
        return email != null && email.contains("@");
    }

   
    public static boolean isValidMobile(String mobile) {
        return mobile != null && countDigits(mobile.trim()) >= 10;
    }
public static boolean doPasswordsMatch(String password, String confirmPassword) {
    return password != null && password.equals(confirmPassword);
}
public static boolean isGenderSelected(javax.swing.JRadioButton male, javax.swing.JRadioButton female) {
    return male.isSelected() || female.isSelected();
}

    public static String validateAll(String name, String email, String mobile) {
        if (!isValidName(name)) {
            return "Name must be at least 2 characters.";
        }
        if (!isValidEmail(email)) {
            return "Email must contain '@'.";
        }
        if (!isValidMobile(mobile)) {
            return "Mobile number must contain at least 10 digits.";
        }
        return null; 
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
