
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guntass Kaur
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form adminlogin
     */
    public welcome() {
        initComponents();
        getContentPane().setBackground(new Color(240, 248, 255));
        setSize(500, 500);
        setTitle("Welcome");
        setLocationRelativeTo(null);
      //  setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbt1.setBackground(new java.awt.Color(255, 165, 0));
        jbt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbt1.setForeground(new java.awt.Color(255, 255, 255));
        jbt1.setText("Admin Login");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt1);
        jbt1.setBounds(140, 300, 180, 45);

        jbt2.setBackground(new java.awt.Color(30, 144, 255));
        jbt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbt2.setForeground(new java.awt.Color(255, 255, 255));
        jbt2.setText("User Login");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt2);
        jbt2.setBounds(140, 160, 180, 45);

        jbt3.setBackground(new java.awt.Color(60, 179, 113));
        jbt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbt3.setForeground(new java.awt.Color(255, 255, 255));
        jbt3.setText("User Signup");
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt3);
        jbt3.setBounds(140, 230, 180, 45);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 99, 235));
        jLabel2.setText("WELCOME TO ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 240, 40);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("SWIFTMILES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 70, 300, 45);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        UserSignup obj1 = new UserSignup();
        obj1.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        AdminLogin obj = new AdminLogin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        UserLogin obj = new UserLogin();
        obj.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    // End of variables declaration//GEN-END:variables
}
